language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
branches:
  only:
  - master
script:
- sbt clean coverage test && sbt coverageReport && sbt coverageAggregate
after_success:
- sbt codacyCoverage
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
before_cache:
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.github.gseitz
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
notifications:
  email:
  - fgwei521@gmail.com
env:
  global:
    secure: TwQHCetB0T08EJxeW4gWruAXbQh02VSE3yvlwAmLBrAuu3XW3gO7Ae7fRFagXphioXLN0MJ6T2IIdSD0KTMo2VG54PmywTmH9arDAx+kSG7P3wQoI/Wooiys8lsovh9EdS5CZsTha/kVyhkb+xNAJk0n+QmKpiTLsqgEq3pxvt8d/QQL12COu9LPiwYFeaZvAaVp8v4j6rUX5AvbzMeeEI/1+Ay7pgEQwvHs6GzhpvR+yESsWqKX9dhsyozy1uKYKcF5eCdPBenvypGp/N1PxQN1XG5gRHfgzZoPJiloIPT1AXsI3IUZKqF60qvfHAXqPwEKOGfpn9Psxk0gYWtvHSAP9PqrUI/YgRRLsnzY8UBqoat1k47yfwcZ3NOPKEFyx7x1t2Jl1ixTctkyvvfdsof23ZTZv0C7z/+F93/tL8v6eZuAPx8TiuUBDeEF/CJiCX24uZZTk/xg8zG8DDuYkftN/v+TrAulMvL9/BYxOt2kbdRlwGPnfXAqRersUUNGqK+EImlrYR+CWKUE9q8R4C4+/Z0gyLoYTgq/x0R8f2m03DauB9LgblULz1n8M8HE106iaaxYziY7hfJddeQfhKH/ZlqtSVv206sB5u3TA20+odxWPFfgS+kmG8JASer26IXZ6Fuw3ud5kcZLUwY/jL8owJflSGOuWMG++jTcRmc=
